### ISSUE TITLE
Arcolinux Tweak Tool won't start

### ISSUE THREAD

**Issue by rendinjast** [arcolinux/arcolinux-tweak-tool#4]
Hi.
when i try to open the app. after typing password and splash-screen, app crashes.
i think problem is related to sddm. I switched to lightdm and deleted sddm(before that i didn't have this issue).
 
im using arcolinux-tweak-tool-dev-git 21.08-33

the error in terminal:
`Traceback (most recent call last):
  File "/usr/share/arcolinux-tweak-tool/arcolinux-tweak-tool.py", line 1586, in <module>
    w = Main()
  File "/usr/share/arcolinux-tweak-tool/arcolinux-tweak-tool.py", line 139, in __init__
    GUI.GUI(self, Gtk, Gdk, GdkPixbuf, base_dir, os, Pango)
  File "/usr/share/arcolinux-tweak-tool/GUI.py", line 242, in GUI
    Sddm_GUI.GUI(self, Gtk, GdkPixbuf, vboxStack17, sddm, Functions)
  File "/usr/share/arcolinux-tweak-tool/Sddm_GUI.py", line 80, in GUI
    sddm.pop_theme_box(self, self.theme_sddm)
  File "/usr/share/arcolinux-tweak-tool/sddm.py", line 106, in pop_theme_box
    name = check_sddm(lines, "Current=").split("=")[1]
  File "/usr/share/arcolinux-tweak-tool/sddm.py", line 10, in check_sddm
    pos = Functions._get_position(lists, value)
  File "/usr/share/arcolinux-tweak-tool/Functions.py", line 229, in _get_position
    position = lists.index(data[0])
IndexError: list index out of range`

**Comment by arcolinuxz** [comment]
We use the standard Sddm configuration files.

Yours will be a bit different.
That is why we have created a script.

type this alias in a terminal and your sddm will be ours again and the ATT will work again

`fix-sddm-config`
